spring:
  messages:
    basename: messages
  #security:
    #user:
      #name: hottj
      #password: root
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"